### ISSUE TITLE
[Request/Scope] create Server abstractions

### ISSUE THREAD

**Issue by lfshr** [nativewrappers/fivem-client#12]
**Describe the solution you'd like**
Discuss/Scope out server abstractions similar to the [C# abstractions](https://github.com/citizenfx/fivem/tree/master/code/client/clrcore/Server)

@AvarianKnight do you have any pre-baked thoughts on a server sided lib?

**Comment by AvarianKnight** [comment]
No, not really, I'm also not entirely sure if the current C# abstraction will be a good starting point, most of the stuff in it is severely outdated, it doesn't look like the C# wrappers have been updated in over a year.

The main thing I want to focus on with a server version is to make sure it is easily tree-shakable (which @nativewrappers/client is not)
